-- Canvas Emporium — Supabase schema.
--
-- Ported from the SQLite DDL that used to live in db.js. Three deliberate
-- changes, all of which delete code elsewhere:
--
--   TEXT holding JSON  →  JSONB       (no JSON.parse/stringify layer)
--   INTEGER 0/1        →  BOOLEAN     (no truthiness coercion)
--   TEXT ISO-8601      →  TIMESTAMPTZ (no string date comparisons)
--
-- Idempotent: safe to run against a database that already has some of it.

CREATE TABLE IF NOT EXISTS users (
  id            INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  username      TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  salt          TEXT NOT NULL,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS families (
  id       TEXT PRIMARY KEY,
  name     TEXT NOT NULL,
  slug     TEXT NOT NULL UNIQUE,
  kicker   TEXT NOT NULL DEFAULT '',
  blurb    TEXT NOT NULL DEFAULT '',
  position INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS categories (
  id        TEXT PRIMARY KEY,
  name      TEXT NOT NULL,
  family_id TEXT NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  slug      TEXT NOT NULL UNIQUE,
  blurb     TEXT NOT NULL DEFAULT '',
  plate     TEXT NOT NULL DEFAULT 'project',
  position  INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS products (
  sku         TEXT PRIMARY KEY,
  name        TEXT NOT NULL,
  family_id   TEXT NOT NULL REFERENCES families(id) ON DELETE CASCADE,
  category_id TEXT NOT NULL REFERENCES categories(id) ON DELETE CASCADE,
  tagline     TEXT NOT NULL DEFAULT '',
  description TEXT NOT NULL DEFAULT '',
  price       INTEGER NOT NULL DEFAULT 0,
  unit        TEXT,
  cogs        INTEGER NOT NULL DEFAULT 0,
  channel     TEXT NOT NULL DEFAULT 'D2C'
              CHECK (channel IN ('D2C', 'B2B', 'D2C/B2B', 'B2B/D2C')),
  moq         INTEGER NOT NULL DEFAULT 1 CHECK (moq >= 1),
  capacity    TEXT,
  weight      TEXT,
  waterproof  TEXT,
  dimensions  TEXT,
  packed      TEXT,
  temperature TEXT,
  materials   JSONB NOT NULL DEFAULT '[]'::jsonb,
  colors      JSONB NOT NULL DEFAULT '[]'::jsonb,
  details     JSONB NOT NULL DEFAULT '[]'::jsonb,
  images      JSONB NOT NULL DEFAULT '[]'::jsonb,
  plate       TEXT NOT NULL DEFAULT 'project',
  badge       TEXT,
  featured    BOOLEAN NOT NULL DEFAULT false,
  hero        BOOLEAN NOT NULL DEFAULT false,
  position    INTEGER NOT NULL DEFAULT 0,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Tents designed in the configurator. A row is written the moment a design is
-- saved or bagged, so nothing is lost if the visitor never enquires; the
-- contact columns fill in later, when they do.
CREATE TABLE IF NOT EXISTS custom_tents (
  id         TEXT PRIMARY KEY,
  family     TEXT NOT NULL,
  headline   TEXT NOT NULL DEFAULT '',
  spec       JSONB NOT NULL,
  quantity   INTEGER NOT NULL DEFAULT 1,
  name       TEXT,
  email      TEXT,
  phone      TEXT,
  basket     JSONB NOT NULL DEFAULT '[]'::jsonb,
  -- false = saved design only, true = an enquiry was submitted against it.
  submitted  BOOLEAN NOT NULL DEFAULT false,
  status     TEXT NOT NULL DEFAULT 'new'
             CHECK (status IN ('new', 'contacted', 'quoted', 'closed')),
  notes      TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_custom_submitted   ON custom_tents(submitted, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_products_category  ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_family    ON products(family_id);
CREATE INDEX IF NOT EXISTS idx_categories_family  ON categories(family_id);

-- The catalogue is always read in this order; the index makes it an index scan
-- rather than a sort of the whole table on every page load.
CREATE INDEX IF NOT EXISTS idx_products_position  ON products(position, sku);

-- Every table is reached only through the Express API using the pooler
-- credentials, which bypass RLS. Enabling it anyway means that if the anon key
-- is ever pointed at this database, it reads nothing by default.
ALTER TABLE users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE families     ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories   ENABLE ROW LEVEL SECURITY;
ALTER TABLE products     ENABLE ROW LEVEL SECURITY;
ALTER TABLE custom_tents ENABLE ROW LEVEL SECURITY;
